"""add_wechat_login_support

Revision ID: 93554fcd038c
Revises: 
Create Date: 2025-10-02 20:32:53.882492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93554fcd038c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add WeChat fields as nullable first
    op.add_column('users', sa.Column('openid', sa.String(length=100), nullable=True, comment='微信openid'))
    op.add_column('users', sa.Column('unionid', sa.String(length=100), nullable=True, comment='微信unionid'))
    op.add_column('users', sa.Column('nickname', sa.String(length=100), nullable=True, comment='昵称'))

    # Create enum type
    loginmethod_enum = sa.Enum('EMAIL', 'WECHAT', 'GITHUB', 'GOOGLE', name='loginmethod')
    loginmethod_enum.create(op.get_bind())

    # Add login_method column with default value for existing users
    op.add_column('users', sa.Column('login_method', loginmethod_enum, nullable=True, comment='登录方式'))
    op.execute("UPDATE users SET login_method = 'EMAIL' WHERE login_method IS NULL")
    op.alter_column('users', 'login_method', nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='用户名')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='邮箱')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='密码哈希')
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_index(op.f('ix_users_unionid'), 'users', ['unionid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_unionid'), table_name='users')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='密码哈希')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='邮箱')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='用户名')
    op.drop_column('users', 'login_method')
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'unionid')
    op.drop_column('users', 'openid')

    # Drop enum type
    loginmethod_enum = sa.Enum('EMAIL', 'WECHAT', 'GITHUB', 'GOOGLE', name='loginmethod')
    loginmethod_enum.drop(op.get_bind())
    # ### end Alembic commands ###