"""add missing fields to agent model

Revision ID: e55da730fb85
Revises: 38aff062c8b4
Create Date: 2025-10-03 14:11:52.427783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55da730fb85'
down_revision: Union[str, None] = '38aff062c8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('memory_window', sa.Integer(), nullable=False, comment='记忆窗口大小'))
    op.add_column('agents', sa.Column('rate_limit_per_day', sa.Integer(), nullable=False, comment='每日请求限制'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'rate_limit_per_day')
    op.drop_column('agents', 'memory_window')
    # ### end Alembic commands ###